# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overthink < Formula
  desc "A dramatic overanalysis engine for your most questionable life decisions"
  homepage "https://github.com/rishichawda/overthinker"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rishichawda/overthinker/releases/download/v0.1.0/overthink_Darwin_x86_64.tar.gz"
      sha256 "b184f8348d571aa58afbd7ae949e400ce64ea83a9ef8f6ab4d41ee22548e35f0"

      define_method(:install) do
        bin.install "overthink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rishichawda/overthinker/releases/download/v0.1.0/overthink_Darwin_arm64.tar.gz"
      sha256 "f103a09f7fdfe102955de685b6d42d66b48ed61e6cb205c6454035aa4cf18c9d"

      define_method(:install) do
        bin.install "overthink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rishichawda/overthinker/releases/download/v0.1.0/overthink_Linux_x86_64.tar.gz"
      sha256 "a9efba404da8c6fc3ab1d39d016bfbb907aa5b7d9b7a76c7c48ded740d3863b8"
      define_method(:install) do
        bin.install "overthink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rishichawda/overthinker/releases/download/v0.1.0/overthink_Linux_arm64.tar.gz"
      sha256 "778a79eb181d01836554f07537ed19d8692204b5af2361de533d5ba7e0eab758"
      define_method(:install) do
        bin.install "overthink"
      end
    end
  end

  test do
    assert_match "overthink -- a dramatic overanalysis engine", shell_output("#{bin}/overthink 2>&1", 1)
  end
end
